### PR TITLE
ISSUE-161: AMI CSV export fails when an ADO has a missing type key

### LINKED ISSUE #161: AMI CSV export fails when an ADO has a missing `type` key
Very edge case but @alliomeria found this one today.

Fix is not hard Drupal\ami\Plugin\Action\AmiStrawberryfieldCSVexport->execute() needs an "isset()"

### PR DESCRIPTION
**Pull request by aksm**
Resolves #161.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@aksm. Since type key is one of two keys required (label/type) for an AMI set. When no type key is set, how would an AMI set from an export work? Could you please elaborate on the solution here? Thanks!

**Comment by aksm** [comment]
@DiegoPino Sorry, that was silly of me. Will convert to draft and continue working on this.

**Comment by aksm** [comment]
Hmm, maybe add an option to the next step to skip the row or generate the CSV only? As a user I'd want to make the decision beforehand.

File: src/Plugin/Action/AmiStrawberryfieldCSVexport.php [hunk 1]
```diff
@@ -362,7 +366,7 @@ protected function sendToFile($output) {
       $data['data'] = $output;
       $data['headers'] = $this->context['sandbox']['headers'];
       $file_id = $this->AmiUtilityService->csv_save($data, 'node_uuid');
-      if ($file_id && $this->configuration['create_ami_set']) {
+      if ($file_id && $this->configuration['create_ami_set'] && $this->tempStore->get('ado_type_exists')) {
```
Comment (DiegoPino) [inline src/Plugin/Action/AmiStrawberryfieldCSVexport.php:369]: @aksm almost (logic seems good). You should not use tempStore like this. The tempStore (this one) is global for a logged in user, and even if you are resetting the value on a new fetch, because you are not giving it a specific name there could be race conditions where this ado_type_exists might end being set (for 6 days) for ado_type_exist == FALSE or two Exports are running at the same time for the same user (we can't control what users do).

See for example how I used it in the saveRows function  $this->tempStore->set($this->getCid(), $rows).
I feel it easier/less permanent to use `$this->context` to pass variable data around during a batch. It is not saved in the DB as permanent and it lives only during the actual batch. 
Said differently: temp store is not a good fit for a flag in this case, please use $this->context to flag ado_type_exists. Thanks

**Review by DiegoPino — CHANGES_REQUESTED** [review]
Better to use ($this->context which is local to this batch) instead of tempstore (which is global to this user, specially when no batch aware id is passed)

File: src/Plugin/Action/AmiStrawberryfieldCSVexport.php (hunk 1 above)
Comment (aksm) [reply src/Plugin/Action/AmiStrawberryfieldCSVexport.php:369]: Ah ok, that makes sense. Will update. Thanks.

**Comment by DiegoPino** [comment]
@aksm did you test this? Could you provide information on how this was tested? Thanks

**Comment by aksm** [comment]
@DiegoPino Yes, I tested by selecting different combinations of ADOs, e.g.:

* 1 ADO with no type key
* Multiple ADOs that included one without the type key
* Multiple ADOs all with type keys

Then I processed with and without the new AMI set option to see that it properly produced the CSV and skipped the AMI set if there's a type missing on any ADOs and gave the user a message.

> @aksm did you test this? Could you provide information on how this was tested? Thanks
